# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f047d97a6f85d5c32014b5e8ac5186d6316266f5107083d2f13952139ac825fe73ad1a96f8857fb7333ad06d685f9c1640d274ea070a96871259a323ed97015

test:
  secret_key_base: 9a9a276f57b00047744e76e3c2947d5791f379705cf7e08b90ba012ed9d0a80c6ccf6bfeac9bac96da313091371164746cee0181f0dc6750993ec7404124482c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
